### ISSUE TITLE
你好，请问您的代码有遇到r2这个指标一直特别小的问题吗？

### ISSUE THREAD

**Issue by joannacatj** [JK-Liu7/AttentionMGT-DTA#6]
由于我的电脑性能比较差，batchsize只能设置为8，会是由于这个问题导致的r2一直在10的-6次方左右吗？

**Comment by vinngs1208** [comment]
你好，请问我能向你咨询前期的处理过程吗？因为我发现运行过程有点问题，感谢~

**Comment by joannacatj** [comment]
> 你好，请问我能向你咨询前期的处理过程吗？因为我发现运行过程有点问题，感谢~

请问是什么问题呢

**Comment by xinxinxin12366666** [comment]
while running protein_process.py, I am facing an issue inside the Protein_graph_process(dataset, fold, dir_output, id_train, id_test) function.
在运行protein_process.py时，我在Protein_graph_process(dataset, fold, dir_output, id_train, id_test)函数中面临一个问题。
I did not find any code which helps to generate pocket_graphs.
我没有找到任何有助于生成pocket_graphs的代码。
can someone help me out to know how are the pocket_graphs generatedin the file protein_process.py the code is loading pocket graphs and at the below pasted line i am facing error.
有人可以帮助我知道如何在文件protein_process.py中生成口袋图形，代码正在加载口袋图形，并在下面粘贴行我面临错误。
protein_graph_train,_ = load_graphs('data/' + dataset + '/processed' + '/pocket_graph/' + str(id) + '.bin')
Protein_graph_train，_ = load_graphs('data/' + dataset + '/processed' + '/pocket_graph/' + str(id) + '.bin')w
我看到您已经预处理成功了可以请教下您关于这个pocket_graph数据怎么获取吗，我没有在数据集上找到这个数据 @ @joannacatj

**Comment by zForestz** [comment]
您好，我在运行代码的过程中也出现以下问题，请问您遇到这个问题了吗？
在蛋白质处理文件中的Protein_embedding_process文件中出现维度问题：Traceback (most recent call last): File "/home/wangxin/DTA/AttentionMGT-DTA/protein_process.py", line 395, in Protein_graph_process(dataset=dataset, fold=fold, id_train=protein_id_train, id_test=protein_id_test, dir_output=dir_output) File "/home/wangxin/DTA/AttentionMGT-DTA/protein_process.py", line 304, in Protein_graph_process np.save(dir_output + '/train/fold/' + str(fold) + '/protein_embedding.npy', proteins_embedding_train) File "<array_function internals>", line 200, in save File "/home/wangxin/anaconda3/envs/pytorch-DTA/lib/python3.9/site-packages/numpy/lib/npyio.py", line 521, in save arr = np.asanyarray(arr) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (19964,) + inhomogeneous 
我输出了一下 每个protein_embedding_train的维度，第0维都不同，在保存文件时维度不同保存的时候就会出错，因为读取的npy文件是作者给出的，没办法进行修改了，希望您能百忙之中抽空帮我解答一下问题，期待您的回复！非常感谢！

**Comment by lichangyaya** [comment]
> while running protein_process.py, I am facing an issue inside the Protein_graph_process(dataset, fold, dir_output, id_train, id_test) function. 在运行protein_process.py时，我在Protein_graph_process(dataset, fold, dir_output, id_train, id_test)函数中面临一个问题。 I did not find any code which helps to generate pocket_graphs. 我没有找到任何有助于生成pocket_graphs的代码。 can someone help me out to know how are the pocket_graphs generatedin the file protein_process.py the code is loading pocket graphs and at the below pasted line i am facing error. 有人可以帮助我知道如何在文件protein_process.py中生成口袋图形，代码正在加载口袋图形，并在下面粘贴行我面临错误。 protein_graph_train,_ = load_graphs('data/' + dataset + '/processed' + '/pocket_graph/' + str(id) + '.bin') Protein_graph_train，_ = load_graphs('data/' + dataset + '/processed' + '/pocket_graph/' + str(id) + '.bin')w 我看到您已经预处理成功了可以请教下您关于这个pocket_graph数据怎么获取吗，我没有在数据集上找到这个数据 @ @joannacatj

我也想问这个问题

**Comment by lichangyaya** [comment]
> > 你好，请问我能向你咨询前期的处理过程吗？因为我发现运行过程有点问题，感谢~
> 
> 请问是什么问题呢

你好，我想问下您是怎么解决PDB_AF2/Q2M2I8.pdb

**Comment by angeload** [comment]
I have the same question. @joannacatj

**Comment by bblb-sjb** [comment]
> 由于我的电脑性能比较差，batchsize只能设置为8，会是由于这个问题导致的r2一直在10的-6次方左右吗？

您好我想问一下他data/Davix里的processed中有ESM_embedding_pocket，但是我看他protein_process.py中使用了ESM_embedding，和ESM_embedding_pocket不一样，请问这个ESM_embedding是怎么我生成的，我从论文中读取了他对uniport中的pbd进行的esm2的处理，但是并没有说具体是怎么处理的，您能解答一下我这个问题吗

**Comment by angeload** [comment]
> > 由于我的电脑性能比较差，batchsize只能设置为8，会是由于这个问题导致的r2一直在10的-6次方左右吗？
> 
> 您好我想问一下他data/Davix里的processed中有ESM_embedding_pocket，但是我看他protein_process.py中使用了ESM_embedding，和ESM_embedding_pocket不一样，请问这个ESM_embedding是怎么我生成的，我从论文中读取了他对uniport中的pbd进行的esm2的处理，但是并没有说具体是怎么处理的，您能解答一下我这个问题吗

I have the same question.

**Comment by upupqianqian** [comment]
你好，我训练了60多个epoch，loss才从0.735下降到0.668，r的平方从5e-05到0.01，请问这个正常吗，loss下降的这么慢正常吗

**Comment by bblb-sjb** [comment]
> 你好，我训练了60多个epoch，loss才从0.735下降到0.668，r的平方从5e-05到0.01，请问这个正常吗，loss下降的这么慢正常吗

那应该是你自己的问题，大概在650轮最好。
```
Training on Davis, fold:1
Epoch		Time		MSE		RMSE		CI		r2
1		338.2		0.71851		0.84765		0.52184		0.00186
MSE improved at epoch  1 ;	best_mse: 0.71850604
2		672.69		0.6213		0.78823		0.62406		0.10358
MSE improved at epoch  2 ;	best_mse: 0.6213007
3		1009.48		0.63453		0.79657		0.69185		0.19261
4		1343.18		0.78804		0.88772		0.70158		0.18175
5		1676.81		0.5552		0.74512		0.71946		0.21468
model has been saved
MSE improved at epoch  5 ;	best_mse: 0.5551988
6		2010.52		0.54099		0.73552		0.72459		0.24102
model has been saved
MSE improved at epoch  6 ;	best_mse: 0.54099154
7		2344.79		0.56821		0.7538		0.73395		0.26291
8		2679.8		0.51267		0.71601		0.74235		0.26899
model has been saved
MSE improved at epoch  8 ;	best_mse: 0.51267076
9		3014.65		0.53715		0.73291		0.74662		0.28444
10		3350.2		0.49913		0.70649		0.74512		0.27123
model has been saved
MSE improved at epoch  10 ;	best_mse: 0.49912947
11		3684.97		0.59459		0.7711		0.75886		0.29591
12		4020.58		0.46626		0.68283		0.77131		0.32595
model has been saved
MSE improved at epoch  12 ;	best_mse: 0.46626085
13		4356.86		0.55538		0.74524		0.77141		0.32872
14		4689.92		0.50944		0.71375		0.77065		0.32065
15		5023.55		0.46043		0.67855		0.77954		0.33824
model has been saved
MSE improved at epoch  15 ;	best_mse: 0.46043083
16		5357.15		0.4547		0.67432		0.77686		0.32661
model has been saved
MSE improved at epoch  16 ;	best_mse: 0.4547045
17		5690.87		0.44925		0.67026		0.77922		0.33406
model has been saved
MSE improved at epoch  17 ;	best_mse: 0.4492497
18		6023.85		0.58687		0.76608		0.77993		0.3159
19		6357.44		0.44637		0.66811		0.78223		0.33424
model has been saved
MSE improved at epoch  19 ;	best_mse: 0.4463707
20		6691.65		0.45362		0.67352		0.7877		0.35712
21		7025.6		0.44647		0.66818		0.78955		0.32525
22		7361.13		0.43501		0.65956		0.79135		0.36941
model has been saved
MSE improved at epoch  22 ;	best_mse: 0.43501356
23		7698.18		0.43182		0.65713		0.7896		0.34477
model has been saved
MSE improved at epoch  23 ;	best_mse: 0.4318245
24		8036.83		0.46952		0.68522		0.79155		0.35701
25		8373.4		0.42616		0.65281		0.79412		0.36326
model has been saved
MSE improved at epoch  25 ;	best_mse: 0.4261638
26		8709.37		0.40033		0.63272		0.79835		0.39689
model has been saved
MSE improved at epoch  26 ;	best_mse: 0.40032905
27		9046.42		0.44054		0.66373		0.7991		0.34304
28		9382.96		0.41973		0.64787		0.79203		0.36607
29		9719.2		0.47403		0.6885		0.79983		0.37105
30		10056.18		0.42036		0.64835		0.80163		0.39142
31		10390.61		0.46906		0.68488		0.80842		0.36977
32		10724.19		0.41877		0.64712		0.80195		0.39623
33		11058.63		0.3937		0.62746		0.80544		0.41278
model has been saved
MSE improved at epoch  33 ;	best_mse: 0.3937039
34		11391.84		0.43844		0.66215		0.81421		0.36886
35		11726.59		0.42086		0.64873		0.80711		0.36416
36		12060.92		0.38433		0.61995		0.81081		0.41152
model has been saved
MSE improved at epoch  36 ;	best_mse: 0.3843334
37		12394.16		0.4043		0.63585		0.81022		0.37005
38		12727.8		0.40663		0.63768		0.80344		0.37998
39		13063.95		0.42301		0.65039		0.81556		0.41153
40		13399.32		0.57936		0.76116		0.81419		0.37217
41		13734.61		0.39979		0.63229		0.81861		0.39207
42		14069.21		0.39389		0.62761		0.81187		0.38626
43		14405.4		0.45021		0.67098		0.81523		0.34674
44		14741.43		0.45533		0.67478		0.8198		0.40597
45		15077.5		0.39025		0.6247		0.81794		0.38434
46		15414.38		0.36075		0.60063		0.82513		0.44273
model has been saved
MSE improved at epoch  46 ;	best_mse: 0.36075303
47		15750.31		0.43705		0.6611		0.82313		0.37855
48		16084.33		0.42556		0.65235		0.82083		0.39002
49		16420.77		0.37069		0.60884		0.81638		0.43081
50		16756.36		0.45161		0.67202		0.8234		0.39162
51		17091.94		0.44248		0.66519		0.82031		0.35786
52		17426.51		0.41834		0.64679		0.82156		0.38783
53		17763.38		0.45848		0.67711		0.82672		0.40752
54		18101.37		0.43504		0.65958		0.81213		0.34104
55		18435.96		0.34915		0.59089		0.83128		0.44366
model has been saved
MSE improved at epoch  55 ;	best_mse: 0.3491521
56		18773.01		0.40573		0.63697		0.83011		0.39065
57		19109.44		0.37136		0.60939		0.82383		0.43516
58		19445.44		0.3915		0.6257		0.82529		0.38299
59		19780.8		0.37039		0.6086		0.82932		0.40441
60		20117.37		0.44884		0.66996		0.82292		0.37086
61		20453.08		0.44192		0.66477		0.82205		0.38284
62		20789.71		0.3775		0.61441		0.82955		0.40105
63		21125.0		0.44729		0.6688		0.82759		0.38581
64		21459.64		0.43136		0.65678		0.81723		0.36776
65		21795.01		0.39677		0.6299		0.8258		0.40084
66		22129.2		0.36777		0.60644		0.82904		0.43702
67		22463.12		0.48261		0.6947		0.83714		0.36861
68		22797.45		0.36789		0.60654		0.82603		0.43662
69		23132.5		0.34918		0.59092		0.82699		0.43654
70		23470.54		0.3688		0.60729		0.83194		0.40063
71		23805.28		0.38271		0.61864		0.81945		0.44214
72		24140.29		0.33891		0.58216		0.82442		0.46425
model has been saved
MSE improved at epoch  72 ;	best_mse: 0.33890513
73		24476.89		0.38498		0.62046		0.82199		0.38424
74		24811.13		0.36637		0.60529		0.81487		0.39855
75		25146.17		0.34934		0.59105		0.83497		0.4434
76		25481.54		0.39907		0.63172		0.8269		0.41605
77		25816.84		0.3516		0.59296		0.82222		0.42775
78		26151.13		0.3558		0.59649		0.83023		0.41523
79		26485.4		0.44245		0.66517		0.83324		0.3795
80		26821.08		0.3766		0.61368		0.83324		0.39226
81		27155.04		0.32411		0.56931		0.83989		0.47083
model has been saved
MSE improved at epoch  81 ;	best_mse: 0.32411078
82		27488.3		0.35104		0.59249		0.82752		0.44223
83		27824.31		0.3728		0.61058		0.82034		0.38945
84		28160.06		0.34702		0.58909		0.8188		0.42937
85		28494.7		0.33753		0.58097		0.81897		0.43948
86		28831.45		0.35187		0.59318		0.82957		0.43143
87		29165.76		0.35684		0.59736		0.83021		0.43456
88		29501.71		0.37567		0.61292		0.82087		0.42782
89		29838.43		0.39842		0.6312		0.81887		0.42143
90		30175.27		0.36159		0.60132		0.82321		0.40644
91		30511.37		0.39414		0.62781		0.82876		0.39402
92		30849.32		0.35217		0.59344		0.82322		0.41835
93		31184.3		0.39552		0.6289		0.81515		0.42565
94		31520.7		0.34349		0.58608		0.82018		0.42721
95		31857.37		0.34456		0.58699		0.81284		0.43757
96		32192.53		0.3462		0.58838		0.81776		0.43036
97		32528.7		0.35319		0.5943		0.82452		0.42254
98		32864.6		0.40856		0.63918		0.83149		0.40198
99		33199.98		0.38956		0.62415		0.82302		0.38746
100		33534.86		0.39823		0.63105		0.81079		0.37268
```
这是我的训练日志，我训练了1000轮，耗时大约5天，最后的指标大概与论文差0.003，也算能接受吧

**Comment by upupqianqian** [comment]
> > 你好，我训练了60多个epoch，loss才从0.735下降到0.668，r的平方从5e-05到0.01，请问这个正常吗，loss下降的这么慢正常吗
> 
> 那应该是你自己的问题，大概在650轮最好。
> 
> ```
> Training on Davis, fold:1
> Epoch		Time		MSE		RMSE		CI		r2
> 1		338.2		0.71851		0.84765		0.52184		0.00186
> MSE improved at epoch  1 ;	best_mse: 0.71850604
> 2		672.69		0.6213		0.78823		0.62406		0.10358
> MSE improved at epoch  2 ;	best_mse: 0.6213007
> 3		1009.48		0.63453		0.79657		0.69185		0.19261
> 4		1343.18		0.78804		0.88772		0.70158		0.18175
> 5		1676.81		0.5552		0.74512		0.71946		0.21468
> model has been saved
> MSE improved at epoch  5 ;	best_mse: 0.5551988
> 6		2010.52		0.54099		0.73552		0.72459		0.24102
> model has been saved
> MSE improved at epoch  6 ;	best_mse: 0.54099154
> 7		2344.79		0.56821		0.7538		0.73395		0.26291
> 8		2679.8		0.51267		0.71601		0.74235		0.26899
> model has been saved
> MSE improved at epoch  8 ;	best_mse: 0.51267076
> 9		3014.65		0.53715		0.73291		0.74662		0.28444
> 10		3350.2		0.49913		0.70649		0.74512		0.27123
> model has been saved
> MSE improved at epoch  10 ;	best_mse: 0.49912947
> 11		3684.97		0.59459		0.7711		0.75886		0.29591
> 12		4020.58		0.46626		0.68283		0.77131		0.32595
> model has been saved
> MSE improved at epoch  12 ;	best_mse: 0.46626085
> 13		4356.86		0.55538		0.74524		0.77141		0.32872
> 14		4689.92		0.50944		0.71375		0.77065		0.32065
> 15		5023.55		0.46043		0.67855		0.77954		0.33824
> model has been saved
> MSE improved at epoch  15 ;	best_mse: 0.46043083
> 16		5357.15		0.4547		0.67432		0.77686		0.32661
> model has been saved
> MSE improved at epoch  16 ;	best_mse: 0.4547045
> 17		5690.87		0.44925		0.67026		0.77922		0.33406
> model has been saved
> MSE improved at epoch  17 ;	best_mse: 0.4492497
> 18		6023.85		0.58687		0.76608		0.77993		0.3159
> 19		6357.44		0.44637		0.66811		0.78223		0.33424
> model has been saved
> MSE improved at epoch  19 ;	best_mse: 0.4463707
> 20		6691.65		0.45362		0.67352		0.7877		0.35712
> 21		7025.6		0.44647		0.66818		0.78955		0.32525
> 22		7361.13		0.43501		0.65956		0.79135		0.36941
> model has been saved
> MSE improved at epoch  22 ;	best_mse: 0.43501356
> 23		7698.18		0.43182		0.65713		0.7896		0.34477
> model has been saved
> MSE improved at epoch  23 ;	best_mse: 0.4318245
> 24		8036.83		0.46952		0.68522		0.79155		0.35701
> 25		8373.4		0.42616		0.65281		0.79412		0.36326
> model has been saved
> MSE improved at epoch  25 ;	best_mse: 0.4261638
> 26		8709.37		0.40033		0.63272		0.79835		0.39689
> model has been saved
> MSE improved at epoch  26 ;	best_mse: 0.40032905
> 27		9046.42		0.44054		0.66373		0.7991		0.34304
> 28		9382.96		0.41973		0.64787		0.79203		0.36607
> 29		9719.2		0.47403		0.6885		0.79983		0.37105
> 30		10056.18		0.42036		0.64835		0.80163		0.39142
> 31		10390.61		0.46906		0.68488		0.80842		0.36977
> 32		10724.19		0.41877		0.64712		0.80195		0.39623
> 33		11058.63		0.3937		0.62746		0.80544		0.41278
> model has been saved
> MSE improved at epoch  33 ;	best_mse: 0.3937039
> 34		11391.84		0.43844		0.66215		0.81421		0.36886
> 35		11726.59		0.42086		0.64873		0.80711		0.36416
> 36		12060.92		0.38433		0.61995		0.81081		0.41152
> model has been saved
> MSE improved at epoch  36 ;	best_mse: 0.3843334
> 37		12394.16		0.4043		0.63585		0.81022		0.37005
> 38		12727.8		0.40663		0.63768		0.80344		0.37998
> 39		13063.95		0.42301		0.65039		0.81556		0.41153
> 40		13399.32		0.57936		0.76116		0.81419		0.37217
> 41		13734.61		0.39979		0.63229		0.81861		0.39207
> 42		14069.21		0.39389		0.62761		0.81187		0.38626
> 43		14405.4		0.45021		0.67098		0.81523		0.34674
> 44		14741.43		0.45533		0.67478		0.8198		0.40597
> 45		15077.5		0.39025		0.6247		0.81794		0.38434
> 46		15414.38		0.36075		0.60063		0.82513		0.44273
> model has been saved
> MSE improved at epoch  46 ;	best_mse: 0.36075303
> 47		15750.31		0.43705		0.6611		0.82313		0.37855
> 48		16084.33		0.42556		0.65235		0.82083		0.39002
> 49		16420.77		0.37069		0.60884		0.81638		0.43081
> 50		16756.36		0.45161		0.67202		0.8234		0.39162
> 51		17091.94		0.44248		0.66519		0.82031		0.35786
> 52		17426.51		0.41834		0.64679		0.82156		0.38783
> 53		17763.38		0.45848		0.67711		0.82672		0.40752
> 54		18101.37		0.43504		0.65958		0.81213		0.34104
> 55		18435.96		0.34915		0.59089		0.83128		0.44366
> model has been saved
> MSE improved at epoch  55 ;	best_mse: 0.3491521
> 56		18773.01		0.40573		0.63697		0.83011		0.39065
> 57		19109.44		0.37136		0.60939		0.82383		0.43516
> 58		19445.44		0.3915		0.6257		0.82529		0.38299
> 59		19780.8		0.37039		0.6086		0.82932		0.40441
> 60		20117.37		0.44884		0.66996		0.82292		0.37086
> 61		20453.08		0.44192		0.66477		0.82205		0.38284
> 62		20789.71		0.3775		0.61441		0.82955		0.40105
> 63		21125.0		0.44729		0.6688		0.82759		0.38581
> 64		21459.64		0.43136		0.65678		0.81723		0.36776
> 65		21795.01		0.39677		0.6299		0.8258		0.40084
> 66		22129.2		0.36777		0.60644		0.82904		0.43702
> 67		22463.12		0.48261		0.6947		0.83714		0.36861
> 68		22797.45		0.36789		0.60654		0.82603		0.43662
> 69		23132.5		0.34918		0.59092		0.82699		0.43654
> 70		23470.54		0.3688		0.60729		0.83194		0.40063
> 71		23805.28		0.38271		0.61864		0.81945		0.44214
> 72		24140.29		0.33891		0.58216		0.82442		0.46425
> model has been saved
> MSE improved at epoch  72 ;	best_mse: 0.33890513
> 73		24476.89		0.38498		0.62046		0.82199		0.38424
> 74		24811.13		0.36637		0.60529		0.81487		0.39855
> 75		25146.17		0.34934		0.59105		0.83497		0.4434
> 76		25481.54		0.39907		0.63172		0.8269		0.41605
> 77		25816.84		0.3516		0.59296		0.82222		0.42775
> 78		26151.13		0.3558		0.59649		0.83023		0.41523
> 79		26485.4		0.44245		0.66517		0.83324		0.3795
> 80		26821.08		0.3766		0.61368		0.83324		0.39226
> 81		27155.04		0.32411		0.56931		0.83989		0.47083
> model has been saved
> MSE improved at epoch  81 ;	best_mse: 0.32411078
> 82		27488.3		0.35104		0.59249		0.82752		0.44223
> 83		27824.31		0.3728		0.61058		0.82034		0.38945
> 84		28160.06		0.34702		0.58909		0.8188		0.42937
> 85		28494.7		0.33753		0.58097		0.81897		0.43948
> 86		28831.45		0.35187		0.59318		0.82957		0.43143
> 87		29165.76		0.35684		0.59736		0.83021		0.43456
> 88		29501.71		0.37567		0.61292		0.82087		0.42782
> 89		29838.43		0.39842		0.6312		0.81887		0.42143
> 90		30175.27		0.36159		0.60132		0.82321		0.40644
> 91		30511.37		0.39414		0.62781		0.82876		0.39402
> 92		30849.32		0.35217		0.59344		0.82322		0.41835
> 93		31184.3		0.39552		0.6289		0.81515		0.42565
> 94		31520.7		0.34349		0.58608		0.82018		0.42721
> 95		31857.37		0.34456		0.58699		0.81284		0.43757
> 96		32192.53		0.3462		0.58838		0.81776		0.43036
> 97		32528.7		0.35319		0.5943		0.82452		0.42254
> 98		32864.6		0.40856		0.63918		0.83149		0.40198
> 99		33199.98		0.38956		0.62415		0.82302		0.38746
> 100		33534.86		0.39823		0.63105		0.81079		0.37268
> ```
> 
> 这是我的训练日志，我训练了1000轮，耗时大约5天，最后的指标大概与论文差0.003，也算能接受吧

好的，谢谢你；那就很奇怪诶，请问你用的是作者给的compound_graph ，ESM_embedding_pocket 和ESM_embedding_protein  pocket_graph这三个数据集吗；我发现作者是不是没有对数据集划分为train和test，没有data/Davis/DTA/fold/1/Davis_train.csv这个文件，我就自己划分了一下，不知道是不是这里出了问题，不知道你是怎么处理的，如果方便的话能不能让我看一看
![image](https://github.com/user-attachments/assets/068dba93-86f8-44dd-9922-1bc1a2717bba)
```
import pandas as pd
from sklearn.model_selection import KFold
import os

# 读取数据集
file_path = 'data/Davis/Davis.csv'
df = pd.read_csv(file_path)

# # 删除有问题的蛋白质数据Q13153
# df = df[df['PROTEIN_ID'] != 'Q13153']

# 定义输出文件夹
output_dir = 'data/Davis/DTA/fold/'

# 创建KFold对象，n_splits=5表示5折
kf = KFold(n_splits=5, shuffle=True, random_state=42)
print(kf)

# 遍历每一折
for i, (train_index, test_index) in enumerate(kf.split(df), 1):
    # 获取训练集和测试集
    train_df = df.iloc[train_index]
    test_df = df.iloc[test_index]

    # 创建对应的文件夹
    fold_dir = os.path.join(output_dir, str(i))
    os.makedirs(fold_dir, exist_ok=True)

    # 保存训练集和测试集
    train_df.to_csv(os.path.join(fold_dir, f'Davis_train.csv'), index=False)
    test_df.to_csv(os.path.join(fold_dir, f'Davis_test.csv'), index=False)

    print(f'Fold {i} created with {len(train_df)} training samples and {len(test_df)} testing samples.') 
    ```

**Comment by upupqianqian** [comment]
大佬，请问你是直接使用作者提供ESM_embedding_pocket 和pocket_graph，还是自己生成的呢？如果是自己生成的，作者似乎没有提供切割蛋白口袋部分的代码，如何切割esm嵌入和蛋白质？能否问一下您是怎么处理的吗

**Comment by CoconutLatte11** [comment]
您好请问，作者是不是很多数据没有给出？ESM_embedding您是怎么处理的？
